### Section A: Data Structures & Control Structures

#### Question 1: List Operations
Create a list of 5 integers. Perform and print the result of various list operations.  

In [1]:
# Create a list of 5 integers
my_list = [40, 10, 30, 20, 50]
print("Original List:", my_list)

# 1. append: Adds an element to the end
my_list.append(60)
print("After append(60):", my_list)

# 2. extend: Appends elements from an iterable to the end
my_list.extend([70, 80])
print("After extend([70, 80]):", my_list)

# 3. insert: Inserts an item at a given index
my_list.insert(2, 25)  # Inserts 25 at index 2
print("After insert(2, 25):", my_list)

# 4. remove: Removes the first item with the specified value
my_list.remove(10)
print("After remove(10):", my_list)

# 5. pop: Removes and returns the item at the given index (default last)
popped_item = my_list.pop()
print(f"After pop(): {my_list} (Popped item: {popped_item})")

# 6. index: Returns the index of the first matched value
idx = my_list.index(30)
print(f"Index of 30: {idx}")

# 7. count: Returns the number of times a value appears
cnt = my_list.count(20)
print(f"Count of 20: {cnt}")

# 8. sort: Sorts the list in ascending order
my_list.sort()
print("After sort():", my_list)

# 9. reverse: Reverses the elements of the list in place
my_list.reverse()
print("After reverse():", my_list)

# 10. clear: Removes all items from the list
my_list.clear()
print("After clear():", my_list)

Original List: [40, 10, 30, 20, 50]
After append(60): [40, 10, 30, 20, 50, 60]
After extend([70, 80]): [40, 10, 30, 20, 50, 60, 70, 80]
After insert(2, 25): [40, 10, 25, 30, 20, 50, 60, 70, 80]
After remove(10): [40, 25, 30, 20, 50, 60, 70, 80]
After pop(): [40, 25, 30, 20, 50, 60, 70] (Popped item: 80)
Index of 30: 2
Count of 20: 1
After sort(): [20, 25, 30, 40, 50, 60, 70]
After reverse(): [70, 60, 50, 40, 30, 25, 20]
After clear(): []


#### Question 2: Tuples
Create a tuple that stores 3 student names. Try changing the second name in the tuple.

In [ ]:
students = ("Amit", "Rahul", "Priya")
print("Original Tuple:", students)

try:
    students[1] = "Rohit"
except TypeError as e:
    print(f"\n[ERROR OCCURRED]: TypeError: {e}")

print("\n--- Explanation ---")
print(
    "Tuples are IMMUTABLE data structures in Python. Once a tuple is created, "
    "its elements cannot be modified, added, or removed. Attempting to item-assign "
    "raises a TypeError."
)

Original Tuple: ('Amit', 'Rahul', 'Priya')

[ERROR OCCURRED]: TypeError: 'tuple' object does not support item assignment

--- Explanation ---
Tuples are IMMUTABLE data structures in Python. Once a tuple is created, its elements cannot be modified, added, or removed. Attempting to item-assign raises a TypeError.


#### Question 3: Sets
Create a set of integers with some duplicate values

In [ ]:
my_set = {10, 20, 30, 20, 40, 10, 50}

print("Printed Set:", my_set)

print("\n--- Explanation ---")
print(
    "Sets in Python automatically filter out duplicate values because a set "
    "is collection of unique elements. Additionally, sets are unordered, meaning "
    "the output may not maintain the exact arrangement order in which elements were added."
)

Printed Set: {50, 20, 40, 10, 30}

--- Explanation ---
Sets in Python automatically filter out duplicate values because a set is collection of unique elements. Additionally, sets are unordered, meaning the output may not maintain the exact arrangement order in which elements were added.


#### Question 4: Dictionaries
Create a dictionary with keys: 'name', 'age', 'city'. Update age and add 'email'.

In [4]:
# Create the initial dictionary
user_info = {"name": "Suresh", "age": 25, "city": "Mumbai"}
print("Initial Dictionary:", user_info)

# Update the age
user_info["age"] = 26

# Add a new key 'email'
user_info["email"] = "suresh@example.com"

# Print the final dictionary
print("Final Dictionary:", user_info)

Initial Dictionary: {'name': 'Suresh', 'age': 25, 'city': 'Mumbai'}
Final Dictionary: {'name': 'Suresh', 'age': 26, 'city': 'Mumbai', 'email': 'suresh@example.com'}


#### Question 5: Conditional Script (Voting Eligibility)
Write a script that checks if a person is eligible to vote (age $\ge$ 18)

In [5]:
# Take age as a variable
age = 20

# Check eligibility
if age >= 18:
    print(f"Age: {age} -> Eligible to vote!")
else:
    print(f"Age: {age} -> Not eligible to vote yet.")

Age: 20 -> Eligible to vote!


#### Question 6: Grade Evaluation
Given a 'marks' variable, print the grade.

In [6]:
# Marks variable
marks = 82

# Grade control flow evaluation
if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "Fail"

print(f"Marks: {marks} -> Grade: {grade}")

Marks: 82 -> Grade: B


#### Question 7: Nested Conditions
Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:
# Input number
num = 14

if num > 0:
    if num % 2 == 0:
        print(f"{num} is Positive and Even.")
    else:
        print(f"{num} is Positive but Odd.")
elif num == 0:
    print(f"{num} is Zero.")
else:
    print(f"{num} is Negative.")

14 is Positive and Even.


### Section B: Numpy

#### Question 8: Create Scalars and Arrays
Create a scalar, a 1D array, and a 2D array.

In [8]:
import numpy as np

# 1. A scalar using np.array(5)
scalar_arr = np.array(5)
print("Scalar:", scalar_arr)
print("Scalar Shape:", scalar_arr.shape)

# 2. A 1D array with values 1 to 5
array_1d = np.arange(1, 6)
print("\n1D Array:", array_1d)

# 3. A 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.arange(10, 70, 10).reshape(2, 3)
print("\n2D Array (2x3):\n", array_2d)

Scalar: 5
Scalar Shape: ()

1D Array: [1 2 3 4 5]

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]


#### Question 9: Random Array Generation
Generate a 4x4 NumPy array of random integers between 0 and 100.

In [9]:
# Generate 4x4 array of random integers between 0 and 100
# Note: high value is exclusive, so we use 101 to include 100 if needed
random_matrix = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Matrix:\n", random_matrix)

4x4 Random Matrix:
 [[16 77 67 55]
 [ 7 73 27 39]
 [69 51 77 59]
 [51 93 34 78]]


#### Question 10: NumPy to Pandas Conversion
Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names.

In [10]:
import pandas as pd

# Create a 3x3 NumPy array
np_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Convert to a pandas DataFrame with specified column names
df_from_np = pd.DataFrame(np_3x3, columns=["A", "B", "C"])

print("Converted Pandas DataFrame:")
print(df_from_np)

Converted Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Section C: Exploring Pandas

#### Question 11: Dataframe Exploration & Manipulation

Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then execute downstream operations.

In [12]:
import numpy as np
import pandas as pd

raw_data = {
    "Name": [
        "Amit",
        "Rahul",
        "Priya",
        "Amit",
        "Sonia",
        "Vijay",
        "Neha",
        "Raj",
        "Anjali",
        "Vikram",
    ],
    "Age": [23, 28, 25, 23, 31, 42, 27, 35, 29, 33],
    "City": [
        "Delhi",
        "Mumbai",
        "Bangalore",
        "Delhi",
        "Chennai",
        "Delhi",
        "Mumbai",
        "Pune",
        "Bangalore",
        "Pune",
    ],
    "Salary": [
        50000,
        62000,
        np.nan,
        50000,
        71000,
        85000,
        np.nan,
        90000,
        58000,
        65000,
    ],  
}

df = pd.DataFrame(raw_data)
print("--- Step 1: Initial Manually Created DataFrame ---")
print(df)
print("-" * 50)

print("\n--- Step 2a: .info() Summary ---")
df.info()

print("\n--- Step 2b: .describe() Statistical Breakdown ---")
print(df.describe())
print("-" * 50)

name_city_df = df[["Name", "City"]]
print("\n--- Step 3: Selected 'Name' and 'City' Columns ---")
print(name_city_df.head())
print("-" * 50)

df_dropped_city = df.drop(columns=["City"])
print("\n--- Step 4: DataFrame After Dropping 'City' Column ---")
print(df_dropped_city.head())
print("-" * 50)

mean_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(mean_salary)
print(f"\n--- Step 5: Filled Missing Salaries with Mean (₹{mean_salary:.2f}) ---")
print(df)
print("-" * 50)

df_cleaned = df.drop_duplicates()
print("\n--- Step 6: Final Cleaned DataFrame (Duplicates Removed) ---")
print(df_cleaned)

--- Step 1: Initial Manually Created DataFrame ---
     Name  Age       City   Salary
0    Amit   23      Delhi  50000.0
1   Rahul   28     Mumbai  62000.0
2   Priya   25  Bangalore      NaN
3    Amit   23      Delhi  50000.0
4   Sonia   31    Chennai  71000.0
5   Vijay   42      Delhi  85000.0
6    Neha   27     Mumbai      NaN
7     Raj   35       Pune  90000.0
8  Anjali   29  Bangalore  58000.0
9  Vikram   33       Pune  65000.0
--------------------------------------------------

--- Step 2a: .info() Summary ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes

--- Step 2b: .describe() Statistical Breakdown ---
             Age        Salary
count 